/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    CellControls: typeof import('./src/components/CellControls.vue')['default']
    CellInfoCard: typeof import('./src/components/CellInfoCard.vue')['default']
    Gene: typeof import('./src/components/Gene.vue')['default']
    Genome: typeof import('./src/components/Genome.vue')['default']
    IconMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    IconMdiClock: typeof import('~icons/mdi/clock')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiContentSave: typeof import('~icons/mdi/content-save')['default']
    IconMdiCrosshairsGps: typeof import('~icons/mdi/crosshairs-gps')['default']
    IconMdiCursorDefault: typeof import('~icons/mdi/cursor-default')['default']
    IconMdiDelete: typeof import('~icons/mdi/delete')['default']
    IconMdiDna: typeof import('~icons/mdi/dna')['default']
    IconMdiFastForward: typeof import('~icons/mdi/fast-forward')['default']
    IconMdiFileDownload: typeof import('~icons/mdi/file-download')['default']
    IconMdiFolderSpecial: typeof import('~icons/mdi/folder-special')['default']
    IconMdiInfo: typeof import('~icons/mdi/info')['default']
    IconMdiLightningBolt: typeof import('~icons/mdi/lightning-bolt')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    IconMdiMenuDown: typeof import('~icons/mdi/menu-down')['default']
    IconMdiMenuRight: typeof import('~icons/mdi/menu-right')['default']
    IconMdiPan: typeof import('~icons/mdi/pan')['default']
    IconMdiPause: typeof import('~icons/mdi/pause')['default']
    IconMdiPlay: typeof import('~icons/mdi/play')['default']
    IconMdiReplay: typeof import('~icons/mdi/replay')['default']
    IconMdiRotateLeft: typeof import('~icons/mdi/rotate-left')['default']
    IconMdiRotateRight: typeof import('~icons/mdi/rotate-right')['default']
    IconMdiSelect: typeof import('~icons/mdi/select')['default']
    IconMdiSkull: typeof import('~icons/mdi/skull')['default']
    IconMdiTrash: typeof import('~icons/mdi/trash')['default']
    IconMdiUndo: typeof import('~icons/mdi/undo')['default']
    InputModeSelector: typeof import('./src/components/InputModeSelector.vue')['default']
    LoadCellButton: typeof import('./src/components/LoadCellButton.vue')['default']
    PlaceCellTooltip: typeof import('./src/components/PlaceCellTooltip.vue')['default']
    SaveCellButton: typeof import('./src/components/SaveCellButton.vue')['default']
    SavedCellPane: typeof import('./src/components/SavedCellPane.vue')['default']
    SimulationCanvas: typeof import('./src/components/SimulationCanvas.vue')['default']
    SimulationControls: typeof import('./src/components/SimulationControls.vue')['default']
  }
}
